image:
  file: gitpod/.gitpod.dockerfile
ports:
  - port: 4000
tasks:
  - before: mix deps.get
    init: gitpod/init.sh
    command: mix ecto.migrate && mix run priv/repo/seeds.exs && iex -S mix phx.server
vscode:
  extensions:
    - JakeBecker.elixir-ls@0.2.25:X1tqg5Hmluq055QJpf0/7A==
    - mjmcloug.vscode-elixir@1.1.0:w8GjsJyyhVFmCZmBc2Ws7A==
